In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
from matplotlib import pyplot as plt
%matplotlib inline

In [3]:

df = pd.read_csv('data.csv')
len(df)

10000

In [154]:

df = pd.read_csv('car_fuel_efficiency.csv.1')
len(df)

9704

In [164]:
df = pd.read_csv('car_fuel_efficiency.csv.1')
df.head(100)

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                   170            3.0       159.0     3413.433759   
1                   130            5.0        97.0     3149.664934   
2                   170            NaN        78.0     3079.038997   
3                   220            4.0         NaN     2542.392402   
4                   210            1.0       140.0     3460.870990   
..                  ...            ...         ...             ...   
95                  200            2.0       232.0     3476.591797   
96                  120            5.0       172.0     3475.004528   
97                  280            2.0       133.0     3398.340992   
98                  250            NaN       109.0     3210.919484   
99                  240            5.0       194.0     3019.882237   

    acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0           17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1           17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2           15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3           20.2        2009     USA    Diesel    All-wheel drive        2.0   
4           14.4        2009  Europe  Gasoline    All-wheel drive        2.0   
..           ...         ...     ...       ...                ...        ...   
95          11.0        2016     USA  Gasoline    All-wheel drive        1.0   
96          13.8        2013     USA    Diesel    All-wheel drive        NaN   
97          15.3        2015  Europe    Diesel    All-wheel drive        1.0   
98          14.6        2021     USA    Diesel    All-wheel drive        0.0   
99          17.5        2017     USA  Gasoline    All-wheel drive        1.0   

    fuel_efficiency_mpg  
0             13.231729  
1             13.688217  
2             14.246341  
3             16.912736  
4             12.488369  
..                  ...  
95            14.674507  
96            12.743224  
97            13.930128  
98            13.128946  
99            14.882406  

[100 rows x 11 columns]

In [163]:
df['vehicle_weight'].nunique()

9704

In [ ]:
df['fuel_type'].sum()

In [161]:
df['fuel_efficiency_mpg'].max()

np.float64(25.96722204888372)

In [160]:
df['fuel_type'].isna().sum()

np.int64(0)

In [162]:
df['horsepower'].median()

np.float64(149.0)

In [159]:
df.isnull().sum()[df.isnull().sum() > 0]

num_cylinders    482
horsepower       708
acceleration     930
num_doors        502
dtype: int64

In [153]:
pd.__version__

'2.3.1'

In [4]:
zeros_array = np.zeros(10)
ones_array = np.ones(10)
constant_array = np.full(10, 3)

In [5]:
my_list = [2, 3, 4]
array_from_list = np.array(my_list)

In [6]:
print(array_from_list)

[2 3 4]


In [7]:
range_array = np.arange(10)  # Creates an array from 0 to 9

In [8]:
linspace_array = np.linspace(0, 1, 11)  # Creates 11 numbers from 0 to 1

In [9]:
print(linspace_array)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [10]:
zeros_matrix = np.zeros((5, 2))
ones_matrix = np.ones((5, 2))
constant_matrix = np.full((5, 2), 3)

In [11]:
print(zeros_matrix)
print(ones_matrix)
print(constant_matrix)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]]


In [12]:
arr = np.array([[2, 3, 4], [4, 5, 6]])
first_row = arr[0]      # Gets the first row
first_col = arr[:, 0]  # Gets the first column

In [13]:
print(arr)
print(first_row)
print(first_col)

[[2 3 4]
 [4 5 6]]
[2 3 4]
[2 4]


In [14]:
np.random.seed(2)  # Set the seed
random_array = np.random.rand(5, 2)  # Generates random numbers between 0 and 1

In [15]:
print(np)
print(random_array)

<module 'numpy' from '/home/codespace/.local/lib/python3.12/site-packages/numpy/__init__.py'>
[[0.4359949  0.02592623]
 [0.54966248 0.43532239]
 [0.4203678  0.33033482]
 [0.20464863 0.61927097]
 [0.29965467 0.26682728]]


In [16]:
arr = arr + 1   # Adds 1 to each element
arr = arr * 2   # Multiplies each element by 2
# Similar operations for division and exponentiation

In [17]:
print(arr)

[[ 6  8 10]
 [10 12 14]]


In [18]:
arr1 = np.ones(4)
arr2 = np.full(4, 3)
result = arr1 + arr2  # Element-wise addition
result = arr1 / arr2  # Element-wise division

In [19]:
print(arr1)
print(arr2)
print(result)

[1. 1. 1. 1.]
[3 3 3 3]
[0.33333333 0.33333333 0.33333333 0.33333333]


In [20]:
arr = np.array([1, 2, 3, 4])
greater_than_2 = arr > 2  # Produces [False, False, True, True]

In [21]:
print(arr)
print(greater_than_2)

[1 2 3 4]
[False False  True  True]


In [22]:
selected_elements = arr[arr > 1]  # Gets elements greater than 1

In [23]:
print(selected_elements)

[2 3 4]


In [24]:
min_value = arr.min()    # Minimum value
max_value = arr.max()    # Maximum value
sum_value = arr.sum()    # Sum of all elements
mean_value = arr.mean()  # Mean (average) value
std_deviation = arr.std()  # Standard deviation

In [25]:
print(min_value)
print(max_value)
print(sum_value)
print(mean_value)
print(std_deviation)


1
4
10
2.5
1.118033988749895


In [26]:
my_array = np.array([1, 2, 3, 4, 5])


In [27]:
print(my_array)

[1 2 3 4 5]


In [29]:
	
my_float_array = np.array([1.1, 2.2, 3.3, 4.4, 5.5], dtype=float)
print(my_float_array)

[1.1 2.2 3.3 4.4 5.5]


In [30]:
my_range_array = np.arange(1, 10, 2)
print(my_range_array)

[1 3 5 7 9]


In [31]:
# argument is the size of the array
# result is an array with 5 zeros
n = np.zeros(5)
# Output:
# array([0., 0., 0., 0., 0.])
print(n)
 
o = np.ones(10)
# Output:
# array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
print(o)

# first argument is the size of the array
# second argument is the element you want to fill the array with
f = np.full(10, 2.5)
print(f)
# Output:
# array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])
 
# create an array with the range from 0 to <argument>
a = np.arange(10)
# Output: 
# array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(a)

b = np.arange(3, 10)
# Output: 
# array([3, 4, 5, 6, 7, 8, 9])
print(b) 

# linspace creates an array filled with numbers between first argument and second argument
c = np.linspace(0, 1, 11)
print(c)
# Output:
# array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5]
[0 1 2 3 4 5 6 7 8 9]
[3 4 5 6 7 8 9]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [32]:
my_list = [1, 2, 3, 5, 7, 12]
my_array = np.array(my_list)
print(my_array)

[ 1  2  3  5  7 12]


In [33]:
	
second_element = my_array[1]
print(second_element)

2


In [34]:
last_element = my_array[-1]
print(last_element)

12


In [35]:
subset_array = my_array[1:4]
print(subset_array)

[2 3 5]


In [36]:
subset_array = my_array[2:]
print(subset_array)

[ 3  5  7 12]


In [37]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [38]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
 
# Element-wise addition
result = arr1 + arr2
print(result)
# Output:
# [[ 6  8]
# [10 12]]
 
# Element-wise multiplication
result = arr1 * arr2
print(result)
# Output:
# [[ 5 12]
#  [21 32]]

[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]


In [39]:
# Calculate the sum of all elements
sum_val = np.sum(arr)
print(sum_val)
# Output:
# 21
 
# Calculate the mean of each column
mean_val = np.mean(arr, axis=0)
print(mean_val)
# Output:
# [2.5 3.5 4.5]

21
[2.5 3.5 4.5]


In [40]:
# creates an array with 5 rows and 2 columns, filled with zeros
x = np.zeros((5, 2))
# Output:
#array([[0., 0.],
#       [0., 0.],
#       [0., 0.],
#       [0., 0.],
#       [0., 0.]])
 
# creates an array from a python list
# here we have a list of lists
y = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
# Output:
# array([[1, 2, 3],
#       [4, 5, 6],
#       [7, 8, 9]])
print(x)
print(y)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [41]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
 
# Accessing a single element
element = arr[0, 2]
print(element)
# Output: 3

3


In [42]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
 
# Accessing a single row
row = arr[1, :]
print(row)
# Output: [4 5 6]

[4 5 6]


In [43]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
 
# Accessing multiple rows
rows = arr[[0, 2], :]
print(rows)

[[1 2 3]
 [7 8 9]]


In [44]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
 
# outputs the first row
n[0]
# Output:
# array([ 1, 20,  3])
print(n)
 
n[0] = [12, 13, 14]
n
# Output:
# array([[12, 13, 14],
#       [ 4,  5,  6],
#       [ 7,  8,  9]])
print(n)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[12 13 14]
 [ 4  5  6]
 [ 7  8  9]]


In [45]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
 
# Accessing a single column
column = arr[:, 1]
print(column)
# Output: [2 5]

[2 5]


In [46]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
 
# Accessing multiple columns
columns = arr[:, [0, 2]]
print(columns)

[[1 3]
 [4 6]
 [7 9]]


In [47]:
n1 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(n1)
 
# outputs the first column
n1[:, 0]
# Output:
# array([1, 4, 7])
print(n1)
 
n1[:, 0] = [12, 13, 14]
print(n1)
# Output:
# array([[12,  2,  3],
#        [13,  5,  6],
#        [14,  8,  9]])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[12  2  3]
 [13  5  6]
 [14  8  9]]


In [48]:
n4 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(n4) 
# outputs the first column
n4[:,0]
# Output: 
# array([1,  4,  7])
print(n4) 

# outputs all the columns
n4[:]
# Output:
# array([[1, 2, 3],
#       [ 4,  5,  6],
#       [ 7,  8,  9]])
print(n4) 
 
n4[:, 2] = [0, 1, 2]
print(n4) 

# Output:
# array([[1, 2,  0],
#       [ 4,  5,  1],
#       [ 7,  8,  2]])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 0]
 [4 5 1]
 [7 8 2]]


In [49]:
# Generate a 1-dimensional array of 5 random integers between 0 and 9
random_integers = np.random.randint(10, size=5)
print(random_integers)
# Output: [2 5 7 1 8]
 
# Generate a 2-dimensional array of shape (3, 4) 
# with random floats between 0 and 1
random_floats = np.random.random((3, 4))
print(random_floats)
# Output:
# [[0.0863851  0.83574087 0.79192621 0.85248822]
#  [0.14040051 0.5714931  0.7586195  0.48544792]
#  [0.4304003  0.76688989 0.68447497 0.54361942]]
 
# Generate a 3-dimensional array of shape (2, 3, 2) 
# with random values from a standard normal distribution
random_normal = np.random.normal(size=(2, 3, 2))
print(random_normal)
# Output:
# [[[-0.27013393  0.54416022]
#   [ 0.02537238 -0.78380969]
#   [-1.25909646 -1.04630766]]
#
#  [[ 0.34262622 -0.66770036]
#   [-0.35426751  0.00569635]
#   [-0.05665257  0.02068191]]]


[4 5 7 3 6]
[[0.51357812 0.18443987 0.78533515 0.85397529]
 [0.49423684 0.84656149 0.07964548 0.50524609]
 [0.0652865  0.42812233 0.09653092 0.12715997]]
[[[-1.38939342  0.49059556]
  [-0.21943638 -0.30837444]
  [-0.45571477 -2.12452767]]

 [[ 0.54979824 -1.16790025]
  [ 1.08006357 -3.4918143 ]
  [ 1.27004848 -0.48921489]]]


In [51]:
# generates a 2-dimensional array of size 5 rows and 2 columns
# with random numbers between 0 and 1 
# rand samples from standard uniform distribution
z = np.random.rand(5, 2)
# Output:
# array([[0.83575882, 0.03277884],
#       [0.78785763, 0.34340225],
#       [0.79212789, 0.75564912],
#       [0.78937584, 0.4326158 ],
#       [0.90909093, 0.82098053]])
print(z)
 
# when you set the random seed it's possible to reproduce the 
# same "random" values
np.random.seed(2)
t = np.random.rand(5, 2)
# Output:
# array([[0.4359949 , 0.02592623],
#       [0.54966248, 0.43532239],
#       [0.4203678 , 0.33033482],
#       [0.20464863, 0.61927097],
#       [0.29965467, 0.26682728]])
print(t)
 
# randn samples from standard normal distribution
np.random.seed(2)
np.random.randn(5, 2)
# Output:
# array([[-0.41675785, -0.05626683],
#       [-2.1361961 ,  1.64027081],
#       [-1.79343559, -0.84174737],
#       [ 0.50288142, -1.24528809],
#       [-1.05795222, -0.90900761]])
w =  np.random.randn(5, 2)
# creates random numbers between 0 and 100
np.random.seed(2)
z = 100 * np.random.rand(5, 2)
# Output:
# array([[43.59949021,  2.59262318],
#       [54.96624779, 43.53223926],
#       [42.03678021, 33.0334821 ],
#       [20.4648634 , 61.92709664],
#       [29.96546737, 26.68272751]])
print(z) 
# creates an array of random integer numbers
np.random.seed(2)
q = np.random.randint(low=0, high=100, size=(5, 2))
print(q)
# Output:
# array([[40, 15],
#       [72, 22],
#       [43, 82],
#       [75,  7],
#       [34, 49]])

[[0.20464863 0.61927097]
 [0.29965467 0.26682728]
 [0.62113383 0.52914209]
 [0.13457995 0.51357812]
 [0.18443987 0.78533515]]
[[0.4359949  0.02592623]
 [0.54966248 0.43532239]
 [0.4203678  0.33033482]
 [0.20464863 0.61927097]
 [0.29965467 0.26682728]]
[[43.59949021  2.59262318]
 [54.96624779 43.53223926]
 [42.03678021 33.0334821 ]
 [20.4648634  61.92709664]
 [29.96546737 26.68272751]]
[[40 15]
 [72 22]
 [43 82]
 [75  7]
 [34 49]]


In [52]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
 
# Element-wise addition
result = arr1 + arr2
print(result)
# Output: [5 7 9]
 
# Element-wise subtraction
result = arr1 - arr2
print(result)
# Output: [-3 -3 -3]

[5 7 9]
[-3 -3 -3]


In [53]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
 
# Element-wise multiplication
result = arr1 * arr2
print(result)
# Output: [4 10 18]
 
# Element-wise division
result = arr1 / arr2
print(result)
# Output: [0.25 0.4  0.5]

[ 4 10 18]
[0.25 0.4  0.5 ]


In [54]:
arr = np.array([0, np.pi/2, np.pi])
 
# Calculate the sine of each element
result = np.sin(arr)
print(result)
# Output: [0.         1.         1.2246468e-16]
 
# Calculate the exponential of each element
result = np.exp(arr)
print(result)
# Output: [ 1.          4.81047738 23.14069263]

[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.          4.81047738 23.14069263]


In [56]:
a = np.arange(5)
print(a)
# Output:
# array([0, 1, 2, 3, 4])
 
# adds 1 to every element in the array
# be careful, you cannot do this with a normal python list
a + 1
# Output:
# array([1, 2, 3, 4, 5])
print(a)
 
a * 2
# Output:
# array([0, 2, 4, 6, 8])
print(a)

a * 100
# Output:
# array([  0, 100, 200, 300, 400])
print(a)

a / 100
# Output:
# array([0.  , 0.01, 0.02, 0.03, 0.04])
 
 
print((10 + (a * 2)) ** 2)
# Output:
# array([100, 144, 196, 256, 324])
 
b = (10 + (a * 2)) ** 2 / 100
print(b)
# Output:
# array([1.  , 1.44, 1.96, 2.56, 3.24])
 
# adds element-wise both arrays
a + b
print(a + b)
# Output:
# array([1.  , 2.44, 3.96, 5.56, 7.24])

[0 1 2 3 4]
[0 1 2 3 4]
[0 1 2 3 4]
[0 1 2 3 4]
[100 144 196 256 324]
[1.   1.44 1.96 2.56 3.24]
[1.   2.44 3.96 5.56 7.24]


In [57]:
arr = np.array([1, 2, 3, 4, 5])
 
# Compare elements with 3
result = arr > 3
print(result)
# Output: [False False False  True  True]

[False False False  True  True]


In [58]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([3, 2, 1])
 
# Compare elements of arr1 and arr2
result = arr1 == arr2
print(result)
# Output: [False  True False]

[False  True False]


In [59]:
arr = np.array([1, 2, 3, 4, 5])
 
# Compare elements that are greater than 2 and less than 5
result = (arr > 2) & (arr < 5)
print(result)
# Output: [False False  True  True False]

[False False  True  True False]


In [60]:
a = np.arange(5)
b = (10 + (a * 2)) ** 2 / 100
print(b)
# compare numbers element-wise
print(a >= 2)
# Output:
# array([False, False,  True,  True,  True])
 
print(a > b)
# Output:
# array([False, False,  True,  True,  True])
 
# checks which elements of a are greater than b
# a > b -> returns an boolean array
# a[a > b] returns the elements where the boolean array is true
# that are the elements 2, 3, and 4
print(a[a > b])
# Output:
# array([2, 3, 4])
 
a[2], a[3], a[4]
# Output:
(2, 3, 4)

[1.   1.44 1.96 2.56 3.24]
[False False  True  True  True]
[False False  True  True  True]
[2 3 4]


(2, 3, 4)

In [61]:
# there are some operations that instead of returning a new array, 
# it returns a single number
# e.g. min() returns the smallest number 
print(a.min())
# Output: 0
 
print(a.max())
# Output: 4
 
print(a.sum())
# Output: 10
 
print(a.mean())
# Output: 2
 
# standard deviation
print(a.std())
# Output: 1.4142135623730951
 
j = n = np.array([
   [12, 13,  0],
    [ 4,  5,  1],
    [ 7,  8,  2]
])
print(j)
 
# this also works for 2-dimensional arrays
n.sum()
# Output: 52
print(n.sum()) 
n.min()
print(n.min())
# Output: 0

0
4
10
2.0
1.4142135623730951
[[12 13  0]
 [ 4  5  1]
 [ 7  8  2]]
52
0


In [62]:
print(np.full(10, 2.5))


[2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5]


In [63]:
ones = np.ones(10)
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [64]:
array = np.full(10, 0.0)
array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [65]:
array = np.repeat(0.0, 10) 
array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [66]:
array = np.repeat([0.0, 1.0], 5)
array

array([0., 0., 0., 0., 0., 1., 1., 1., 1., 1.])

In [67]:
array = np.repeat([0.0, 1.0], [2, 3])
array

array([0., 0., 1., 1., 1.])

In [68]:
el = array[1]
print(el)

0.0


In [69]:
array[[4, 2, 0]]

array([1., 1., 0.])

In [70]:
array[1] = 1
print(array)

[0. 1. 1. 1. 1.]


In [71]:
elements = [1, 2, 3, 4]
array = np.array(elements)
array

array([1, 2, 3, 4])

In [72]:
zeros = np.zeros(10, dtype=np.uint8)
zeros

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8)

In [73]:
for i in np.arange(5):
    print(i)

0
1
2
3
4


In [74]:
thresholds = np.linspace(0, 1, 11)
thresholds

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [76]:
zeros = np.zeros((5, 2), dtype=np.float32)
zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)

In [77]:
print(zeros.shape)

(5, 2)


In [78]:
numbers = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

numbers = np.array(numbers)

In [79]:
print(numbers[0, 1])

2


In [80]:
numbers[0, 1] = 10
numbers

array([[ 1, 10,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [81]:
numbers[:, 2] = [9, 9, 9]


In [82]:
np.random.rand(5, 2)

array([[0.20464863, 0.61927097],
       [0.29965467, 0.26682728],
       [0.62113383, 0.52914209],
       [0.13457995, 0.51357812],
       [0.18443987, 0.78533515]])

In [83]:
np.random.seed(2)
arr = np.random.rand(5, 2)
arr

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [84]:
np.random.seed(2)
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [85]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5, 2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

In [86]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5, 2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

In [88]:
rng = np.arange(5)
rng

array([0, 1, 2, 3, 4])

In [89]:
rng * 2

array([0, 2, 4, 6, 8])

In [90]:
(rng - 1) * 3 / 2 + 1

array([-0.5,  1. ,  2.5,  4. ,  5.5])

In [91]:
np.random.seed(2)
noise = 0.01 * np.random.rand(5)
noise

array([0.00435995, 0.00025926, 0.00549662, 0.00435322, 0.00420368])

In [92]:
numbers = np.arange(5)
numbers

array([0, 1, 2, 3, 4])

In [93]:
result = numbers + noise
result

array([0.00435995, 1.00025926, 2.00549662, 3.00435322, 4.00420368])

In [94]:
result.round(4)

array([0.0044, 1.0003, 2.0055, 3.0044, 4.0042])

In [95]:
np.random.seed(2)
pred = np.random.rand(3).round(2)
pred

array([0.44, 0.03, 0.55])

In [96]:
square = pred * pred
square

array([0.1936, 0.0009, 0.3025])

In [97]:
square = pred ** 2
square

array([0.1936, 0.0009, 0.3025])

In [98]:
np.exp(pred)

array([1.55270722, 1.03045453, 1.73325302])

In [99]:
np.log(pred)

array([-0.82098055, -3.5065579 , -0.597837  ])

In [100]:
np.sqrt(pred)

array([0.66332496, 0.17320508, 0.74161985])

In [101]:
np.random.seed(2)
pred = np.random.rand(3).round(2)
pred

array([0.44, 0.03, 0.55])

In [102]:
result = pred >= 0.5
result

array([False, False,  True])

In [103]:
np.random.seed(2)

In [104]:
pred1 = np.random.rand(3).round(2)
pred1

array([0.44, 0.03, 0.55])

In [105]:
pred2 = np.random.rand(3).round(2)
pred2

array([0.44, 0.42, 0.33])

In [106]:
pred1 >= pred2

array([ True, False,  True])

In [108]:
pred1 = np.random.rand(3) >= 0.3
pred1

array([ True, False,  True])

In [109]:
np.random.seed(2)

In [110]:
pred2 = np.random.rand(3) >= 0.4
pred2

array([ True, False,  True])

In [111]:
pred1 & pred2

array([ True, False,  True])

In [112]:
np.random.seed(2)
pred = np.random.rand(3).round(2)
pred_sum = pred.sum()
pred

array([0.44, 0.03, 0.55])

In [113]:
pred_sum


np.float64(1.02)

In [114]:
print('min = %.2f' % pred.min())
print('mean = %.2f' % pred.mean())
print('max = %.2f' % pred.max())
print('std = %.2f' % pred.std())

min = 0.03
mean = 0.34
max = 0.55
std = 0.22


In [115]:
np.random.seed(2)
matrix = np.random.rand(4, 3).round(2)
matrix

array([[0.44, 0.03, 0.55],
       [0.44, 0.42, 0.33],
       [0.2 , 0.62, 0.3 ],
       [0.27, 0.62, 0.53]])

In [116]:
matrix.max()

np.float64(0.62)

In [117]:
matrix.max(axis=1)

array([0.55, 0.44, 0.62, 0.62])

In [118]:
matrix.max(axis=0)

array([0.44, 0.62, 0.55])

In [119]:
matrix.sum(axis=1)

array([1.02, 1.19, 1.12, 1.42])

In [120]:
np.random.seed(2)
pred = np.random.rand(4).round(2)
pred

array([0.44, 0.03, 0.55, 0.44])

In [121]:
np.sort(pred)

array([0.03, 0.44, 0.44, 0.55])

In [122]:
pred

array([0.44, 0.03, 0.55, 0.44])

In [123]:
pred.sort()

In [124]:
np.random.seed(2)
pred = np.random.rand(4).round(2)
pred


array([0.44, 0.03, 0.55, 0.44])

In [126]:
idx = pred.argsort()
idx
pred[idx]

array([0.03, 0.44, 0.44, 0.55])

In [127]:
pred[idx]

array([0.03, 0.44, 0.44, 0.55])

In [128]:
rng = np.arange(12)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [129]:
rng.shape


(12,)

In [130]:
rng.reshape(4, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [132]:
rng.reshape(4, 3, order='F')

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [133]:
rng.reshape(4, 4)

ValueError: cannot reshape array of size 12 into shape (4,4)

In [134]:
vec = np.arange(3)
vec


array([0, 1, 2])

In [135]:
mat = np.arange(6).reshape(3, 2)
mat

array([[0, 1],
       [2, 3],
       [4, 5]])

In [136]:
np.concatenate([vec, vec])

array([0, 1, 2, 0, 1, 2])

In [137]:
np.hstack([vec, vec])

array([0, 1, 2, 0, 1, 2])

In [138]:
np.hstack([mat, mat])

array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [4, 5, 4, 5]])

In [139]:
np.concatenate([mat, mat])

array([[0, 1],
       [2, 3],
       [4, 5],
       [0, 1],
       [2, 3],
       [4, 5]])

In [140]:
np.column_stack([vec, mat])

array([[0, 0, 1],
       [1, 2, 3],
       [2, 4, 5]])

In [141]:
np.column_stack([vec, vec])

array([[0, 0],
       [1, 1],
       [2, 2]])

In [142]:
np.vstack([vec, vec])

array([[0, 1, 2],
       [0, 1, 2]])

In [143]:
np.vstack([mat, mat])

array([[0, 1],
       [2, 3],
       [4, 5],
       [0, 1],
       [2, 3],
       [4, 5]])

In [144]:
mat.T

array([[0, 2, 4],
       [1, 3, 5]])

In [145]:
np.vstack([vec, mat.T])

array([[0, 1, 2],
       [0, 2, 4],
       [1, 3, 5]])

In [146]:
mat = np.arange(15).reshape(5, 3)
mat

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [147]:
mat[:3]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [148]:
mat[1:3, :2]

array([[3, 4],
       [6, 7]])

In [149]:
mat[:, :2]

array([[ 0,  1],
       [ 3,  4],
       [ 6,  7],
       [ 9, 10],
       [12, 13]])

In [150]:
mat[1:3, :2]

array([[3, 4],
       [6, 7]])

In [151]:
mat[[3, 0, 1]]

array([[ 9, 10, 11],
       [ 0,  1,  2],
       [ 3,  4,  5]])

In [152]:
mat[mat[:, 0] % 2 == 1]

array([[ 3,  4,  5],
       [ 9, 10, 11]])